# site settings
title: Nicolas
subtitle: Data Science
email: coronelnicolasjuan@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: NicoUIcreator.github.io
author:
street_address: 
city: Madrid
state: Madrid
zip_code: 28100
country: Spain
phone: +34 621 05 31 29

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/nicouicreator
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/nicolasjuancoronel
  Twitter: https://twitter.com/nicolasjcoronel
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
